spring:
    proflies:
      active:
       - dev
---
spring:
    proflies: dev  #开发环境
    application:
      name: microservicecloud-config-sang-dev
---
spring:
    proflies: test #测试环境
    application:
      name: microservicecloud-config-sang-test
#请保存为UTF-8格式


